"""Add api_endpoint column to APILink

Revision ID: 105d3da4a0d8
Revises: 
Create Date: 2025-06-15 16:32:28.579496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105d3da4a0d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_endpoint', sa.String(length=500), nullable=True))
        batch_op.drop_column('pi_endpoint')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pi_endpoint', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('api_endpoint')

    # ### end Alembic commands ###
